In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, confusion_matrix
from sklearn.ensemble import RandomForestClassifier

In [6]:
AApre = pd.read_csv("AApre2.csv")

# Convert the target variable to an integer type
AApre['r23'] = AApre['r23'].astype(int)

# Prepare the data for training and testing
X = AApre.drop(['r23'], axis=1)
y = AApre['r23']

predictors = ['r3','r12','r15','r16','r17','r18','r28_1', 'r28_2','r28_3','f26','d5' ]
X_selected = X[predictors]
X_selected

,r3,r12,r15,r16,r17,r18,r28_1,r28_2,r28_3,f26,d5
0,91.0,4.428571,6.0,6.000000,13.0,6.000000,1,0,0,1.0,4
1,48.0,3.000000,4.0,4.727273,1.0,3.333333,0,0,1,1.0,4
2,48.0,3.571429,5.0,5.272727,5.0,5.000000,1,0,0,1.0,5
3,16.0,4.571429,7.0,6.636364,13.0,6.500000,1,0,0,1.0,5
4,58.0,4.714286,7.0,6.454545,13.0,6.000000,1,0,0,0.0,3
...,...,...,...,...,...,...,...,...,...,...,...
352,7.5,4.571429,7.0,5.545455,11.5,5.666667,1,0,0,1.0,3
353,13.0,3.428571,6.0,5.363636,13.0,5.333333,0,0,1,0.0,4
354,5.0,4.142857,6.0,6.181818,12.0,6.000000,0,0,0,1.0,5
355,48.0,3.166667,3.0,4.909091,8.5,3.333333,0,0,0,1.0,6
356,22.0,3.142857,5.0,5.363636,8.5,3.000000,0,0,1,1.0,4

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)

# Make predictions on the test set
y_pred = rf.predict(X_test)

# Calculate the accuracy and confusion matrix
accuracy = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
conf_mat = confusion_matrix(y_test, y_pred)

print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 0.7916666666666666
F1 Score: 0.8
Precision: 0.7894736842105263
Recall: 0.8108108108108109

In [11]:
c_sample = pd.read_csv("C_predictors_no_manual2.csv")

Xc_test = c_sample[predictors]
yc_test = c_sample['r23']
Xc_test

,r3,r12,r15,r16,r17,r18,r28_1,r28_2,r28_3,f26,d5
0,1.0,3.857143,6.0,5.363636,8.0,4.166667,1,0,0,0.000000,3
1,36.0,4.000000,6.0,5.454545,12.5,5.666667,1,0,0,0.000000,3
2,28.0,3.000000,4.0,4.000000,3.0,4.000000,0,1,0,0.000000,3
3,24.0,3.285714,6.0,4.272727,6.0,4.333333,0,0,1,0.000000,3
4,5.0,2.571429,6.0,4.818182,-1.0,3.500000,0,0,1,0.081967,2
...,...,...,...,...,...,...,...,...,...,...,...
229,24.0,3.571429,4.0,3.181818,-3.5,4.166667,0,0,1,0.081967,3
230,12.0,4.428571,6.0,5.545455,9.5,4.666667,1,0,0,0.000000,4
231,10.0,4.142857,7.0,5.636364,12.5,5.500000,1,0,0,0.000000,3
232,3.0,2.714286,4.0,3.000000,-3.0,3.166667,0,0,0,0.000000,3
233,10.0,4.571429,6.0,4.818182,9.0,5.666667,1,0,0,0.081967,2

In [12]:
yc_pred = rf.predict(Xc_test)
# Calculate the accuracy and confusion matrix
accuracy = accuracy_score(yc_test, yc_pred)
f1 = f1_score(yc_test, yc_pred)
precision = precision_score(yc_test, yc_pred)
recall = recall_score(yc_test, yc_pred)
conf_mat = confusion_matrix(yc_test, yc_pred)

print("Accuracy:", accuracy)
print("F1 Score:", f1)
print("Precision:", precision)
print("Recall:", recall)

Accuracy: 0.7094017094017094
F1 Score: 0.5466666666666666
Precision: 0.6949152542372882
Recall: 0.45054945054945056